export const REST_API_ACTION = "REST_API_ACTION";
export const REST_API_START = "REST_API_START";
export const REST_API_END = "REST_API_END";
export const REST_API_ACCESS_DENIED = "REST_API_ACCESS_DENIED";
export const REST_API_ERROR = "REST_API_ERROR";