import {
  REST_API_START,
  REST_API_END,
  REST_API_ACCESS_DENIED,
  REST_API_ERROR
} from "../_actions/RestApiTypes";

export const FETCH_CUSTOMER_DETAILS = "FETCH_CUSTOMER_DETAILS";
export const SET_CUSTOMER_DETAILS = "SET_CUSTOMER_DETAILS";
export const SET_MENU = "SET_MENU";
export const FETCH_MENU = "FETCH_MENU";
export const FETCH_STATE_LIST = "FETCH_STATE_LIST";
export const SET_STATE_LIST = "SET_STATE_LIST";
export const FETCH_DISTRICT_LIST = "FETCH_DISTRICT_LIST";
export const SET_DISTRICT_LIST = "SET_DISTRICT_LIST";

// //1. SystemFlow
// export const REST_API_START_SYSTEMFLOW_ACTION = REST_API_START + "_" + REST_API_DOMAIN_SYSTEMFLOW;
// export const REST_API_END_SYSTEMFLOW_ACTION = REST_API_END + "_" + REST_API_DOMAIN_SYSTEMFLOW;
// export const REST_API_ACCESS_DENIED_SYSTEMFLOW_ACTION = REST_API_ACCESS_DENIED + "_" + REST_API_DOMAIN_SYSTEMFLOW;
// export const REST_API_ERROR_SYSTEMFLOW_ACTION = REST_API_ERROR + "_" + REST_API_DOMAIN_SYSTEMFLOW;
